version: '3.3'

services:
  rabbitMq:
    image: rabbitmq:3.7-management
    hostname: localhost
    container_name: rabbitmq_server
    environment:
      - RABBITMQ_ERL_COOKIE=jupiterbakakeu
    network_mode: "host"
    tty: true
    ports:
      - 15672:15672
      - 5672:5672
    labels:
      NAME: "rabbitMQ"

  DummyOPCUASkill:
    build:
      context: ./ressources/dummymachine/
      dockerfile: Dockerfile
    image: dummyopcuaskill
    hostname: localhost
    container_name: DummyOPCUASkill
    network_mode: "host"
    tty: true
    ports:
      - 4840:4840
    labels:
      NAME: "DummyOPCUASkill"
  
  SkillVis:
    build:
      context: ./skillvisualisation/
      dockerfile: Dockerfile
    image: skillvis
    hostname: localhost
    container_name: SkillVis
    network_mode: "host"
    tty: true
    ports:
      - 8080:8080
    labels:
      NAME: "SkillVis"