version: '3.3'

services:
  rabbitMq:
    image: rabbitmq:3.7-management
    hostname: localhost
    container_name: rabbitmq_server
    environment:
      - RABBITMQ_ERL_COOKIE=jupiterbakakeu
    networks:
      - rabbitmq_network
    tty: true
    ports:
      - 15672:15672
      - 5672:5672
    labels:
      NAME: "rabbitMQ"

  DummyOPCUASkill:
    build:
      context: ./Ressources/DummyMachine/
      dockerfile: Dockerfile
    image: DummyOPCUASkill
    hostname: localhost
    container_name: DummyOPCUASkill
    networks:
      - rabbitmq_network
    tty: true
    ports:
      - 8080:8080
    labels:
      NAME: "DummyOPCUASkill"
  
  SkillVis:
    build:
      context: ./SkillVisualisation/
      dockerfile: Dockerfile
    image: skillvis
    hostname: localhost
    container_name: SkillVis
    networks:
      - rabbitmq_network
    tty: true
    ports:
      - 8080:8080
    labels:
      NAME: "SkillVis"

networks:
  rabbitmq_network:
    driver: overlay